// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Aya.Contract.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Sprava.CompiledModels
{
    public static class FileEntityUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref Guid Id(FileEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Host>k__BackingField")]
        public static extern ref string Host(FileEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Login>k__BackingField")]
        public static extern ref string Login(FileEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
        public static extern ref string Name(FileEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Password>k__BackingField")]
        public static extern ref string Password(FileEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Path>k__BackingField")]
        public static extern ref string Path(FileEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Type>k__BackingField")]
        public static extern ref FileType Type(FileEntity @this);
    }
}
