// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Aya.Contract.Models;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Json;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Sprava.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class FileEntityEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Aya.Contract.Models.FileEntity",
                typeof(FileEntity),
                baseEntityType,
                propertyCount: 7,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(FileEntity).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FileEntity).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.SetGetter(
                Guid (FileEntity instance) => FileEntityUnsafeAccessors.Id(instance),
                bool (FileEntity instance) => FileEntityUnsafeAccessors.Id(instance) == new Guid("00000000-0000-0000-0000-000000000000"));
            id.SetSetter(
                FileEntity (FileEntity instance, Guid value) =>
                {
                    FileEntityUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                FileEntity (FileEntity instance, Guid value) =>
                {
                    FileEntityUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                Guid (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<Guid>(0) : (entry.FlaggedAsTemporary(0) && FileEntityUnsafeAccessors.Id(((FileEntity)(entry.Entity))) == new Guid("00000000-0000-0000-0000-000000000000") ? entry.ReadTemporaryValue<Guid>(0) : FileEntityUnsafeAccessors.Id(((FileEntity)(entry.Entity))))),
                Guid (IInternalEntry entry) => FileEntityUnsafeAccessors.Id(((FileEntity)(entry.Entity))),
                Guid (IInternalEntry entry) => entry.ReadOriginalValue<Guid>(id, 0),
                Guid (IInternalEntry entry) => ((InternalEntityEntry)(entry)).ReadRelationshipSnapshotValue<Guid>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            id.TypeMapping = SqliteGuidTypeMapping.Default;
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<Guid>(id));
            id.SetComparer(new ValueComparer<Guid>(
                bool (Guid c1, Guid c2) => c1 == c2,
                int (Guid c) => ((object)c).GetHashCode(),
                Guid (Guid c) => c));

            var host = runtimeEntityType.AddProperty(
                "Host",
                typeof(string),
                propertyInfo: typeof(FileEntity).GetProperty("Host", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FileEntity).GetField("<Host>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 1000);
            host.SetGetter(
                string (FileEntity instance) => FileEntityUnsafeAccessors.Host(instance),
                bool (FileEntity instance) => FileEntityUnsafeAccessors.Host(instance) == null);
            host.SetSetter(
                FileEntity (FileEntity instance, string value) =>
                {
                    FileEntityUnsafeAccessors.Host(instance) = value;
                    return instance;
                });
            host.SetMaterializationSetter(
                FileEntity (FileEntity instance, string value) =>
                {
                    FileEntityUnsafeAccessors.Host(instance) = value;
                    return instance;
                });
            host.SetAccessors(
                string (IInternalEntry entry) => FileEntityUnsafeAccessors.Host(((FileEntity)(entry.Entity))),
                string (IInternalEntry entry) => FileEntityUnsafeAccessors.Host(((FileEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(host, 1),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(host));
            host.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            host.TypeMapping = SqliteStringTypeMapping.Default;

            var login = runtimeEntityType.AddProperty(
                "Login",
                typeof(string),
                propertyInfo: typeof(FileEntity).GetProperty("Login", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FileEntity).GetField("<Login>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 255);
            login.SetGetter(
                string (FileEntity instance) => FileEntityUnsafeAccessors.Login(instance),
                bool (FileEntity instance) => FileEntityUnsafeAccessors.Login(instance) == null);
            login.SetSetter(
                FileEntity (FileEntity instance, string value) =>
                {
                    FileEntityUnsafeAccessors.Login(instance) = value;
                    return instance;
                });
            login.SetMaterializationSetter(
                FileEntity (FileEntity instance, string value) =>
                {
                    FileEntityUnsafeAccessors.Login(instance) = value;
                    return instance;
                });
            login.SetAccessors(
                string (IInternalEntry entry) => FileEntityUnsafeAccessors.Login(((FileEntity)(entry.Entity))),
                string (IInternalEntry entry) => FileEntityUnsafeAccessors.Login(((FileEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(login, 2),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(login));
            login.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            login.TypeMapping = SqliteStringTypeMapping.Default;

            var name = runtimeEntityType.AddProperty(
                "Name",
                typeof(string),
                propertyInfo: typeof(FileEntity).GetProperty("Name", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FileEntity).GetField("<Name>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 255);
            name.SetGetter(
                string (FileEntity instance) => FileEntityUnsafeAccessors.Name(instance),
                bool (FileEntity instance) => FileEntityUnsafeAccessors.Name(instance) == null);
            name.SetSetter(
                FileEntity (FileEntity instance, string value) =>
                {
                    FileEntityUnsafeAccessors.Name(instance) = value;
                    return instance;
                });
            name.SetMaterializationSetter(
                FileEntity (FileEntity instance, string value) =>
                {
                    FileEntityUnsafeAccessors.Name(instance) = value;
                    return instance;
                });
            name.SetAccessors(
                string (IInternalEntry entry) => FileEntityUnsafeAccessors.Name(((FileEntity)(entry.Entity))),
                string (IInternalEntry entry) => FileEntityUnsafeAccessors.Name(((FileEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(name, 3),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(name));
            name.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            name.TypeMapping = SqliteStringTypeMapping.Default;

            var password = runtimeEntityType.AddProperty(
                "Password",
                typeof(string),
                propertyInfo: typeof(FileEntity).GetProperty("Password", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FileEntity).GetField("<Password>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 512);
            password.SetGetter(
                string (FileEntity instance) => FileEntityUnsafeAccessors.Password(instance),
                bool (FileEntity instance) => FileEntityUnsafeAccessors.Password(instance) == null);
            password.SetSetter(
                FileEntity (FileEntity instance, string value) =>
                {
                    FileEntityUnsafeAccessors.Password(instance) = value;
                    return instance;
                });
            password.SetMaterializationSetter(
                FileEntity (FileEntity instance, string value) =>
                {
                    FileEntityUnsafeAccessors.Password(instance) = value;
                    return instance;
                });
            password.SetAccessors(
                string (IInternalEntry entry) => FileEntityUnsafeAccessors.Password(((FileEntity)(entry.Entity))),
                string (IInternalEntry entry) => FileEntityUnsafeAccessors.Password(((FileEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(password, 4),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(password));
            password.SetPropertyIndexes(
                index: 4,
                originalValueIndex: 4,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            password.TypeMapping = SqliteStringTypeMapping.Default;

            var path = runtimeEntityType.AddProperty(
                "Path",
                typeof(string),
                propertyInfo: typeof(FileEntity).GetProperty("Path", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FileEntity).GetField("<Path>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 1000);
            path.SetGetter(
                string (FileEntity instance) => FileEntityUnsafeAccessors.Path(instance),
                bool (FileEntity instance) => FileEntityUnsafeAccessors.Path(instance) == null);
            path.SetSetter(
                FileEntity (FileEntity instance, string value) =>
                {
                    FileEntityUnsafeAccessors.Path(instance) = value;
                    return instance;
                });
            path.SetMaterializationSetter(
                FileEntity (FileEntity instance, string value) =>
                {
                    FileEntityUnsafeAccessors.Path(instance) = value;
                    return instance;
                });
            path.SetAccessors(
                string (IInternalEntry entry) => FileEntityUnsafeAccessors.Path(((FileEntity)(entry.Entity))),
                string (IInternalEntry entry) => FileEntityUnsafeAccessors.Path(((FileEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(path, 5),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(path));
            path.SetPropertyIndexes(
                index: 5,
                originalValueIndex: 5,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            path.TypeMapping = SqliteStringTypeMapping.Default;

            var type = runtimeEntityType.AddProperty(
                "Type",
                typeof(FileType),
                propertyInfo: typeof(FileEntity).GetProperty("Type", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FileEntity).GetField("<Type>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            type.SetGetter(
                FileType (FileEntity instance) => FileEntityUnsafeAccessors.Type(instance),
                bool (FileEntity instance) => object.Equals(((object)(FileEntityUnsafeAccessors.Type(instance))), ((object)(FileType.Local))));
            type.SetSetter(
                FileEntity (FileEntity instance, FileType value) =>
                {
                    FileEntityUnsafeAccessors.Type(instance) = value;
                    return instance;
                });
            type.SetMaterializationSetter(
                FileEntity (FileEntity instance, FileType value) =>
                {
                    FileEntityUnsafeAccessors.Type(instance) = value;
                    return instance;
                });
            type.SetAccessors(
                FileType (IInternalEntry entry) => FileEntityUnsafeAccessors.Type(((FileEntity)(entry.Entity))),
                FileType (IInternalEntry entry) => FileEntityUnsafeAccessors.Type(((FileEntity)(entry.Entity))),
                FileType (IInternalEntry entry) => entry.ReadOriginalValue<FileType>(type, 6),
                FileType (IInternalEntry entry) => entry.GetCurrentValue<FileType>(type));
            type.SetPropertyIndexes(
                index: 6,
                originalValueIndex: 6,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            type.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<FileType>(
                    bool (FileType v1, FileType v2) => object.Equals(((object)(v1)), ((object)(v2))),
                    int (FileType v) => ((object)v).GetHashCode(),
                    FileType (FileType v) => v),
                keyComparer: new ValueComparer<FileType>(
                    bool (FileType v1, FileType v2) => object.Equals(((object)(v1)), ((object)(v2))),
                    int (FileType v) => ((object)v).GetHashCode(),
                    FileType (FileType v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"),
                converter: new ValueConverter<FileType, int>(
                    int (FileType value) => ((int)(value)),
                    FileType (int value) => ((FileType)(value))),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<FileType, int>(
                    JsonInt32ReaderWriter.Instance,
                    new ValueConverter<FileType, int>(
                        int (FileType value) => ((int)(value)),
                        FileType (int value) => ((FileType)(value)))));
            type.SetSentinelFromProviderValue(0);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var id = runtimeEntityType.FindProperty("Id");
            var host = runtimeEntityType.FindProperty("Host");
            var login = runtimeEntityType.FindProperty("Login");
            var name = runtimeEntityType.FindProperty("Name");
            var password = runtimeEntityType.FindProperty("Password");
            var path = runtimeEntityType.FindProperty("Path");
            var type = runtimeEntityType.FindProperty("Type");
            var key = runtimeEntityType.FindKey(new[] { id });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<Guid>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<Guid>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((FileEntity)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid, string, string, string, string, string, FileType>(((ValueComparer<Guid>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<Guid>(id)), (source.GetCurrentValue<string>(host) == null ? null : ((ValueComparer<string>)(((IProperty)host).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(host))), (source.GetCurrentValue<string>(login) == null ? null : ((ValueComparer<string>)(((IProperty)login).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(login))), (source.GetCurrentValue<string>(name) == null ? null : ((ValueComparer<string>)(((IProperty)name).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(name))), (source.GetCurrentValue<string>(password) == null ? null : ((ValueComparer<string>)(((IProperty)password).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(password))), (source.GetCurrentValue<string>(path) == null ? null : ((ValueComparer<string>)(((IProperty)path).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(path))), ((ValueComparer<FileType>)(((IProperty)type).GetValueComparer())).Snapshot(source.GetCurrentValue<FileType>(type)))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<Guid>(((ValueComparer<Guid>)(((IProperty)id).GetValueComparer())).Snapshot(default(Guid))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<Guid>(default(Guid)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((FileEntity)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid>(((ValueComparer<Guid>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<Guid>(id)))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 7,
                navigationCount: 0,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 7,
                shadowCount: 0,
                relationshipCount: 1,
                storeGeneratedCount: 1));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Files");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
