// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Update.Internal;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Sprava.CompiledModels
{
    public partial class SpravaDbContextModel
    {
        private SpravaDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("9efc4554-9eed-4526-be0c-2b48226b1694"), entityTypeCount: 5)
        {
        }

        partial void Initialize()
        {
            var fileEntity = FileEntityEntityType.Create(this);
            var toDoEntity = ToDoEntityEntityType.Create(this);
            var eventEntity = EventEntityEntityType.Create(this);
            var migrationEntity = MigrationEntityEntityType.Create(this);
            var credentialEntity = CredentialEntityEntityType.Create(this);

            FileEntityEntityType.CreateAnnotations(fileEntity);
            ToDoEntityEntityType.CreateAnnotations(toDoEntity);
            EventEntityEntityType.CreateAnnotations(eventEntity);
            MigrationEntityEntityType.CreateAnnotations(migrationEntity);
            CredentialEntityEntityType.CreateAnnotations(credentialEntity);

            AddAnnotation("ProductVersion", "10.0.1");
            AddRuntimeAnnotation("Relational:RelationalModelFactory", () => CreateRelationalModel());
        }

        private IRelationalModel CreateRelationalModel()
        {
            var relationalModel = new RelationalModel(this);

            var fileEntity = FindEntityType("Aya.Contract.Models.FileEntity")!;

            var defaultTableMappings = new List<TableMappingBase<ColumnMappingBase>>();
            fileEntity.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings);
            var ayaContractModelsFileEntityTableBase = new TableBase("Aya.Contract.Models.FileEntity", null, relationalModel);
            var hostColumnBase = new ColumnBase<ColumnMappingBase>("Host", "TEXT", ayaContractModelsFileEntityTableBase);
            ayaContractModelsFileEntityTableBase.Columns.Add("Host", hostColumnBase);
            var idColumnBase = new ColumnBase<ColumnMappingBase>("Id", "TEXT", ayaContractModelsFileEntityTableBase);
            ayaContractModelsFileEntityTableBase.Columns.Add("Id", idColumnBase);
            var loginColumnBase = new ColumnBase<ColumnMappingBase>("Login", "TEXT", ayaContractModelsFileEntityTableBase);
            ayaContractModelsFileEntityTableBase.Columns.Add("Login", loginColumnBase);
            var nameColumnBase = new ColumnBase<ColumnMappingBase>("Name", "TEXT", ayaContractModelsFileEntityTableBase);
            ayaContractModelsFileEntityTableBase.Columns.Add("Name", nameColumnBase);
            var passwordColumnBase = new ColumnBase<ColumnMappingBase>("Password", "TEXT", ayaContractModelsFileEntityTableBase);
            ayaContractModelsFileEntityTableBase.Columns.Add("Password", passwordColumnBase);
            var pathColumnBase = new ColumnBase<ColumnMappingBase>("Path", "TEXT", ayaContractModelsFileEntityTableBase);
            ayaContractModelsFileEntityTableBase.Columns.Add("Path", pathColumnBase);
            var typeColumnBase = new ColumnBase<ColumnMappingBase>("Type", "INTEGER", ayaContractModelsFileEntityTableBase);
            ayaContractModelsFileEntityTableBase.Columns.Add("Type", typeColumnBase);
            relationalModel.DefaultTables.Add("Aya.Contract.Models.FileEntity", ayaContractModelsFileEntityTableBase);
            var ayaContractModelsFileEntityMappingBase = new TableMappingBase<ColumnMappingBase>(fileEntity, ayaContractModelsFileEntityTableBase, null);
            ayaContractModelsFileEntityTableBase.AddTypeMapping(ayaContractModelsFileEntityMappingBase, false);
            defaultTableMappings.Add(ayaContractModelsFileEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase, fileEntity.FindProperty("Id")!, ayaContractModelsFileEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)hostColumnBase, fileEntity.FindProperty("Host")!, ayaContractModelsFileEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)loginColumnBase, fileEntity.FindProperty("Login")!, ayaContractModelsFileEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nameColumnBase, fileEntity.FindProperty("Name")!, ayaContractModelsFileEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)passwordColumnBase, fileEntity.FindProperty("Password")!, ayaContractModelsFileEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)pathColumnBase, fileEntity.FindProperty("Path")!, ayaContractModelsFileEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)typeColumnBase, fileEntity.FindProperty("Type")!, ayaContractModelsFileEntityMappingBase);

            var tableMappings = new List<TableMapping>();
            fileEntity.SetRuntimeAnnotation("Relational:TableMappings", tableMappings);
            var filesTable = new Table("Files", null, relationalModel);
            var idColumn = new Column("Id", "TEXT", filesTable);
            filesTable.Columns.Add("Id", idColumn);
            idColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(idColumn);
            var hostColumn = new Column("Host", "TEXT", filesTable);
            filesTable.Columns.Add("Host", hostColumn);
            hostColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(hostColumn);
            var loginColumn = new Column("Login", "TEXT", filesTable);
            filesTable.Columns.Add("Login", loginColumn);
            loginColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(loginColumn);
            var nameColumn = new Column("Name", "TEXT", filesTable);
            filesTable.Columns.Add("Name", nameColumn);
            nameColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(nameColumn);
            var passwordColumn = new Column("Password", "TEXT", filesTable);
            filesTable.Columns.Add("Password", passwordColumn);
            passwordColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(passwordColumn);
            var pathColumn = new Column("Path", "TEXT", filesTable);
            filesTable.Columns.Add("Path", pathColumn);
            pathColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(pathColumn);
            var typeColumn = new Column("Type", "INTEGER", filesTable);
            filesTable.Columns.Add("Type", typeColumn);
            typeColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(typeColumn);
            relationalModel.Tables.Add(("Files", null), filesTable);
            var filesTableMapping = new TableMapping(fileEntity, filesTable, null);
            filesTable.AddTypeMapping(filesTableMapping, false);
            tableMappings.Add(filesTableMapping);
            RelationalModel.CreateColumnMapping(idColumn, fileEntity.FindProperty("Id")!, filesTableMapping);
            RelationalModel.CreateColumnMapping(hostColumn, fileEntity.FindProperty("Host")!, filesTableMapping);
            RelationalModel.CreateColumnMapping(loginColumn, fileEntity.FindProperty("Login")!, filesTableMapping);
            RelationalModel.CreateColumnMapping(nameColumn, fileEntity.FindProperty("Name")!, filesTableMapping);
            RelationalModel.CreateColumnMapping(passwordColumn, fileEntity.FindProperty("Password")!, filesTableMapping);
            RelationalModel.CreateColumnMapping(pathColumn, fileEntity.FindProperty("Path")!, filesTableMapping);
            RelationalModel.CreateColumnMapping(typeColumn, fileEntity.FindProperty("Type")!, filesTableMapping);
            var pK_Files = new UniqueConstraint("PK_Files", filesTable, new[] { idColumn });
            filesTable.PrimaryKey = pK_Files;
            pK_Files.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<Guid>(pK_Files));
            var pK_FilesKey = RelationalModel.GetKey(this,
                "Aya.Contract.Models.FileEntity",
                new[] { "Id" });
            pK_Files.MappedKeys.Add(pK_FilesKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_FilesKey).Add(pK_Files);
            filesTable.UniqueConstraints.Add("PK_Files", pK_Files);

            var toDoEntity = FindEntityType("Hestia.Contract.Models.ToDoEntity")!;

            var defaultTableMappings0 = new List<TableMappingBase<ColumnMappingBase>>();
            toDoEntity.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings0);
            var hestiaContractModelsToDoEntityTableBase = new TableBase("Hestia.Contract.Models.ToDoEntity", null, relationalModel);
            var annuallyDaysColumnBase = new ColumnBase<ColumnMappingBase>("AnnuallyDays", "TEXT", hestiaContractModelsToDoEntityTableBase);
            hestiaContractModelsToDoEntityTableBase.Columns.Add("AnnuallyDays", annuallyDaysColumnBase);
            var childrenCompletionTypeColumnBase = new ColumnBase<ColumnMappingBase>("ChildrenCompletionType", "INTEGER", hestiaContractModelsToDoEntityTableBase);
            hestiaContractModelsToDoEntityTableBase.Columns.Add("ChildrenCompletionType", childrenCompletionTypeColumnBase);
            var colorColumnBase = new ColumnBase<ColumnMappingBase>("Color", "TEXT", hestiaContractModelsToDoEntityTableBase);
            hestiaContractModelsToDoEntityTableBase.Columns.Add("Color", colorColumnBase);
            var createdDateTimeColumnBase = new ColumnBase<ColumnMappingBase>("CreatedDateTime", "TEXT", hestiaContractModelsToDoEntityTableBase);
            hestiaContractModelsToDoEntityTableBase.Columns.Add("CreatedDateTime", createdDateTimeColumnBase);
            var currentCircleOrderIndexColumnBase = new ColumnBase<ColumnMappingBase>("CurrentCircleOrderIndex", "INTEGER", hestiaContractModelsToDoEntityTableBase);
            hestiaContractModelsToDoEntityTableBase.Columns.Add("CurrentCircleOrderIndex", currentCircleOrderIndexColumnBase);
            var daysOffsetColumnBase = new ColumnBase<ColumnMappingBase>("DaysOffset", "INTEGER", hestiaContractModelsToDoEntityTableBase);
            hestiaContractModelsToDoEntityTableBase.Columns.Add("DaysOffset", daysOffsetColumnBase);
            var descriptionColumnBase = new ColumnBase<ColumnMappingBase>("Description", "TEXT", hestiaContractModelsToDoEntityTableBase);
            hestiaContractModelsToDoEntityTableBase.Columns.Add("Description", descriptionColumnBase);
            var descriptionTypeColumnBase = new ColumnBase<ColumnMappingBase>("DescriptionType", "INTEGER", hestiaContractModelsToDoEntityTableBase);
            hestiaContractModelsToDoEntityTableBase.Columns.Add("DescriptionType", descriptionTypeColumnBase);
            var dueDateColumnBase = new ColumnBase<ColumnMappingBase>("DueDate", "TEXT", hestiaContractModelsToDoEntityTableBase);
            hestiaContractModelsToDoEntityTableBase.Columns.Add("DueDate", dueDateColumnBase);
            var iconColumnBase = new ColumnBase<ColumnMappingBase>("Icon", "TEXT", hestiaContractModelsToDoEntityTableBase);
            hestiaContractModelsToDoEntityTableBase.Columns.Add("Icon", iconColumnBase);
            var idColumnBase0 = new ColumnBase<ColumnMappingBase>("Id", "TEXT", hestiaContractModelsToDoEntityTableBase);
            hestiaContractModelsToDoEntityTableBase.Columns.Add("Id", idColumnBase0);
            var isBookmarkColumnBase = new ColumnBase<ColumnMappingBase>("IsBookmark", "INTEGER", hestiaContractModelsToDoEntityTableBase);
            hestiaContractModelsToDoEntityTableBase.Columns.Add("IsBookmark", isBookmarkColumnBase);
            var isCompletedColumnBase = new ColumnBase<ColumnMappingBase>("IsCompleted", "INTEGER", hestiaContractModelsToDoEntityTableBase);
            hestiaContractModelsToDoEntityTableBase.Columns.Add("IsCompleted", isCompletedColumnBase);
            var isFavoriteColumnBase = new ColumnBase<ColumnMappingBase>("IsFavorite", "INTEGER", hestiaContractModelsToDoEntityTableBase);
            hestiaContractModelsToDoEntityTableBase.Columns.Add("IsFavorite", isFavoriteColumnBase);
            var isRequiredCompleteInDueDateColumnBase = new ColumnBase<ColumnMappingBase>("IsRequiredCompleteInDueDate", "INTEGER", hestiaContractModelsToDoEntityTableBase);
            hestiaContractModelsToDoEntityTableBase.Columns.Add("IsRequiredCompleteInDueDate", isRequiredCompleteInDueDateColumnBase);
            var lastCompletedColumnBase = new ColumnBase<ColumnMappingBase>("LastCompleted", "TEXT", hestiaContractModelsToDoEntityTableBase)
            {
                IsNullable = true
            };
            hestiaContractModelsToDoEntityTableBase.Columns.Add("LastCompleted", lastCompletedColumnBase);
            var linkColumnBase = new ColumnBase<ColumnMappingBase>("Link", "TEXT", hestiaContractModelsToDoEntityTableBase);
            hestiaContractModelsToDoEntityTableBase.Columns.Add("Link", linkColumnBase);
            var monthlyDaysColumnBase = new ColumnBase<ColumnMappingBase>("MonthlyDays", "TEXT", hestiaContractModelsToDoEntityTableBase);
            hestiaContractModelsToDoEntityTableBase.Columns.Add("MonthlyDays", monthlyDaysColumnBase);
            var monthsOffsetColumnBase = new ColumnBase<ColumnMappingBase>("MonthsOffset", "INTEGER", hestiaContractModelsToDoEntityTableBase);
            hestiaContractModelsToDoEntityTableBase.Columns.Add("MonthsOffset", monthsOffsetColumnBase);
            var nameColumnBase0 = new ColumnBase<ColumnMappingBase>("Name", "TEXT", hestiaContractModelsToDoEntityTableBase);
            hestiaContractModelsToDoEntityTableBase.Columns.Add("Name", nameColumnBase0);
            var normalizeNameColumnBase = new ColumnBase<ColumnMappingBase>("NormalizeName", "TEXT", hestiaContractModelsToDoEntityTableBase);
            hestiaContractModelsToDoEntityTableBase.Columns.Add("NormalizeName", normalizeNameColumnBase);
            var orderIndexColumnBase = new ColumnBase<ColumnMappingBase>("OrderIndex", "INTEGER", hestiaContractModelsToDoEntityTableBase);
            hestiaContractModelsToDoEntityTableBase.Columns.Add("OrderIndex", orderIndexColumnBase);
            var parentIdColumnBase = new ColumnBase<ColumnMappingBase>("ParentId", "TEXT", hestiaContractModelsToDoEntityTableBase)
            {
                IsNullable = true
            };
            hestiaContractModelsToDoEntityTableBase.Columns.Add("ParentId", parentIdColumnBase);
            var referenceIdColumnBase = new ColumnBase<ColumnMappingBase>("ReferenceId", "TEXT", hestiaContractModelsToDoEntityTableBase)
            {
                IsNullable = true
            };
            hestiaContractModelsToDoEntityTableBase.Columns.Add("ReferenceId", referenceIdColumnBase);
            var remindDaysBeforeColumnBase = new ColumnBase<ColumnMappingBase>("RemindDaysBefore", "INTEGER", hestiaContractModelsToDoEntityTableBase);
            hestiaContractModelsToDoEntityTableBase.Columns.Add("RemindDaysBefore", remindDaysBeforeColumnBase);
            var typeColumnBase0 = new ColumnBase<ColumnMappingBase>("Type", "INTEGER", hestiaContractModelsToDoEntityTableBase);
            hestiaContractModelsToDoEntityTableBase.Columns.Add("Type", typeColumnBase0);
            var typeOfPeriodicityColumnBase = new ColumnBase<ColumnMappingBase>("TypeOfPeriodicity", "INTEGER", hestiaContractModelsToDoEntityTableBase);
            hestiaContractModelsToDoEntityTableBase.Columns.Add("TypeOfPeriodicity", typeOfPeriodicityColumnBase);
            var weeklyDaysColumnBase = new ColumnBase<ColumnMappingBase>("WeeklyDays", "TEXT", hestiaContractModelsToDoEntityTableBase);
            hestiaContractModelsToDoEntityTableBase.Columns.Add("WeeklyDays", weeklyDaysColumnBase);
            var weeksOffsetColumnBase = new ColumnBase<ColumnMappingBase>("WeeksOffset", "INTEGER", hestiaContractModelsToDoEntityTableBase);
            hestiaContractModelsToDoEntityTableBase.Columns.Add("WeeksOffset", weeksOffsetColumnBase);
            var yearsOffsetColumnBase = new ColumnBase<ColumnMappingBase>("YearsOffset", "INTEGER", hestiaContractModelsToDoEntityTableBase);
            hestiaContractModelsToDoEntityTableBase.Columns.Add("YearsOffset", yearsOffsetColumnBase);
            relationalModel.DefaultTables.Add("Hestia.Contract.Models.ToDoEntity", hestiaContractModelsToDoEntityTableBase);
            var hestiaContractModelsToDoEntityMappingBase = new TableMappingBase<ColumnMappingBase>(toDoEntity, hestiaContractModelsToDoEntityTableBase, null);
            hestiaContractModelsToDoEntityTableBase.AddTypeMapping(hestiaContractModelsToDoEntityMappingBase, false);
            defaultTableMappings0.Add(hestiaContractModelsToDoEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase0, toDoEntity.FindProperty("Id")!, hestiaContractModelsToDoEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)annuallyDaysColumnBase, toDoEntity.FindProperty("AnnuallyDays")!, hestiaContractModelsToDoEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)childrenCompletionTypeColumnBase, toDoEntity.FindProperty("ChildrenCompletionType")!, hestiaContractModelsToDoEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)colorColumnBase, toDoEntity.FindProperty("Color")!, hestiaContractModelsToDoEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)createdDateTimeColumnBase, toDoEntity.FindProperty("CreatedDateTime")!, hestiaContractModelsToDoEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)currentCircleOrderIndexColumnBase, toDoEntity.FindProperty("CurrentCircleOrderIndex")!, hestiaContractModelsToDoEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)daysOffsetColumnBase, toDoEntity.FindProperty("DaysOffset")!, hestiaContractModelsToDoEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)descriptionColumnBase, toDoEntity.FindProperty("Description")!, hestiaContractModelsToDoEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)descriptionTypeColumnBase, toDoEntity.FindProperty("DescriptionType")!, hestiaContractModelsToDoEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)dueDateColumnBase, toDoEntity.FindProperty("DueDate")!, hestiaContractModelsToDoEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)iconColumnBase, toDoEntity.FindProperty("Icon")!, hestiaContractModelsToDoEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)isBookmarkColumnBase, toDoEntity.FindProperty("IsBookmark")!, hestiaContractModelsToDoEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)isCompletedColumnBase, toDoEntity.FindProperty("IsCompleted")!, hestiaContractModelsToDoEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)isFavoriteColumnBase, toDoEntity.FindProperty("IsFavorite")!, hestiaContractModelsToDoEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)isRequiredCompleteInDueDateColumnBase, toDoEntity.FindProperty("IsRequiredCompleteInDueDate")!, hestiaContractModelsToDoEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)lastCompletedColumnBase, toDoEntity.FindProperty("LastCompleted")!, hestiaContractModelsToDoEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)linkColumnBase, toDoEntity.FindProperty("Link")!, hestiaContractModelsToDoEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)monthlyDaysColumnBase, toDoEntity.FindProperty("MonthlyDays")!, hestiaContractModelsToDoEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)monthsOffsetColumnBase, toDoEntity.FindProperty("MonthsOffset")!, hestiaContractModelsToDoEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nameColumnBase0, toDoEntity.FindProperty("Name")!, hestiaContractModelsToDoEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)normalizeNameColumnBase, toDoEntity.FindProperty("NormalizeName")!, hestiaContractModelsToDoEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)orderIndexColumnBase, toDoEntity.FindProperty("OrderIndex")!, hestiaContractModelsToDoEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)parentIdColumnBase, toDoEntity.FindProperty("ParentId")!, hestiaContractModelsToDoEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)referenceIdColumnBase, toDoEntity.FindProperty("ReferenceId")!, hestiaContractModelsToDoEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)remindDaysBeforeColumnBase, toDoEntity.FindProperty("RemindDaysBefore")!, hestiaContractModelsToDoEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)typeColumnBase0, toDoEntity.FindProperty("Type")!, hestiaContractModelsToDoEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)typeOfPeriodicityColumnBase, toDoEntity.FindProperty("TypeOfPeriodicity")!, hestiaContractModelsToDoEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)weeklyDaysColumnBase, toDoEntity.FindProperty("WeeklyDays")!, hestiaContractModelsToDoEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)weeksOffsetColumnBase, toDoEntity.FindProperty("WeeksOffset")!, hestiaContractModelsToDoEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)yearsOffsetColumnBase, toDoEntity.FindProperty("YearsOffset")!, hestiaContractModelsToDoEntityMappingBase);

            var tableMappings0 = new List<TableMapping>();
            toDoEntity.SetRuntimeAnnotation("Relational:TableMappings", tableMappings0);
            var toDosTable = new Table("ToDos", null, relationalModel);
            var idColumn0 = new Column("Id", "TEXT", toDosTable);
            toDosTable.Columns.Add("Id", idColumn0);
            idColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(idColumn0);
            var annuallyDaysColumn = new Column("AnnuallyDays", "TEXT", toDosTable);
            toDosTable.Columns.Add("AnnuallyDays", annuallyDaysColumn);
            annuallyDaysColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(annuallyDaysColumn);
            var childrenCompletionTypeColumn = new Column("ChildrenCompletionType", "INTEGER", toDosTable);
            toDosTable.Columns.Add("ChildrenCompletionType", childrenCompletionTypeColumn);
            childrenCompletionTypeColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<byte>(childrenCompletionTypeColumn);
            var colorColumn = new Column("Color", "TEXT", toDosTable);
            toDosTable.Columns.Add("Color", colorColumn);
            colorColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(colorColumn);
            var createdDateTimeColumn = new Column("CreatedDateTime", "TEXT", toDosTable);
            toDosTable.Columns.Add("CreatedDateTime", createdDateTimeColumn);
            createdDateTimeColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTimeOffset>(createdDateTimeColumn);
            var currentCircleOrderIndexColumn = new Column("CurrentCircleOrderIndex", "INTEGER", toDosTable);
            toDosTable.Columns.Add("CurrentCircleOrderIndex", currentCircleOrderIndexColumn);
            currentCircleOrderIndexColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<uint>(currentCircleOrderIndexColumn);
            var daysOffsetColumn = new Column("DaysOffset", "INTEGER", toDosTable);
            toDosTable.Columns.Add("DaysOffset", daysOffsetColumn);
            daysOffsetColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<ushort>(daysOffsetColumn);
            var descriptionColumn = new Column("Description", "TEXT", toDosTable);
            toDosTable.Columns.Add("Description", descriptionColumn);
            descriptionColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(descriptionColumn);
            var descriptionTypeColumn = new Column("DescriptionType", "INTEGER", toDosTable);
            toDosTable.Columns.Add("DescriptionType", descriptionTypeColumn);
            descriptionTypeColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<byte>(descriptionTypeColumn);
            var dueDateColumn = new Column("DueDate", "TEXT", toDosTable);
            toDosTable.Columns.Add("DueDate", dueDateColumn);
            dueDateColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<DateOnly>(dueDateColumn);
            var iconColumn = new Column("Icon", "TEXT", toDosTable);
            toDosTable.Columns.Add("Icon", iconColumn);
            iconColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(iconColumn);
            var isBookmarkColumn = new Column("IsBookmark", "INTEGER", toDosTable);
            toDosTable.Columns.Add("IsBookmark", isBookmarkColumn);
            isBookmarkColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<bool>(isBookmarkColumn);
            var isCompletedColumn = new Column("IsCompleted", "INTEGER", toDosTable);
            toDosTable.Columns.Add("IsCompleted", isCompletedColumn);
            isCompletedColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<bool>(isCompletedColumn);
            var isFavoriteColumn = new Column("IsFavorite", "INTEGER", toDosTable);
            toDosTable.Columns.Add("IsFavorite", isFavoriteColumn);
            isFavoriteColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<bool>(isFavoriteColumn);
            var isRequiredCompleteInDueDateColumn = new Column("IsRequiredCompleteInDueDate", "INTEGER", toDosTable);
            toDosTable.Columns.Add("IsRequiredCompleteInDueDate", isRequiredCompleteInDueDateColumn);
            isRequiredCompleteInDueDateColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<bool>(isRequiredCompleteInDueDateColumn);
            var lastCompletedColumn = new Column("LastCompleted", "TEXT", toDosTable)
            {
                IsNullable = true
            };
            toDosTable.Columns.Add("LastCompleted", lastCompletedColumn);
            lastCompletedColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTimeOffset>(lastCompletedColumn);
            var linkColumn = new Column("Link", "TEXT", toDosTable);
            toDosTable.Columns.Add("Link", linkColumn);
            linkColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(linkColumn);
            var monthlyDaysColumn = new Column("MonthlyDays", "TEXT", toDosTable);
            toDosTable.Columns.Add("MonthlyDays", monthlyDaysColumn);
            monthlyDaysColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(monthlyDaysColumn);
            var monthsOffsetColumn = new Column("MonthsOffset", "INTEGER", toDosTable);
            toDosTable.Columns.Add("MonthsOffset", monthsOffsetColumn);
            monthsOffsetColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<ushort>(monthsOffsetColumn);
            var nameColumn0 = new Column("Name", "TEXT", toDosTable);
            toDosTable.Columns.Add("Name", nameColumn0);
            nameColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(nameColumn0);
            var normalizeNameColumn = new Column("NormalizeName", "TEXT", toDosTable);
            toDosTable.Columns.Add("NormalizeName", normalizeNameColumn);
            normalizeNameColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(normalizeNameColumn);
            var orderIndexColumn = new Column("OrderIndex", "INTEGER", toDosTable);
            toDosTable.Columns.Add("OrderIndex", orderIndexColumn);
            orderIndexColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<uint>(orderIndexColumn);
            var parentIdColumn = new Column("ParentId", "TEXT", toDosTable)
            {
                IsNullable = true
            };
            toDosTable.Columns.Add("ParentId", parentIdColumn);
            parentIdColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(parentIdColumn);
            var referenceIdColumn = new Column("ReferenceId", "TEXT", toDosTable)
            {
                IsNullable = true
            };
            toDosTable.Columns.Add("ReferenceId", referenceIdColumn);
            referenceIdColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(referenceIdColumn);
            var remindDaysBeforeColumn = new Column("RemindDaysBefore", "INTEGER", toDosTable);
            toDosTable.Columns.Add("RemindDaysBefore", remindDaysBeforeColumn);
            remindDaysBeforeColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<uint>(remindDaysBeforeColumn);
            var typeColumn0 = new Column("Type", "INTEGER", toDosTable);
            toDosTable.Columns.Add("Type", typeColumn0);
            typeColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(typeColumn0);
            var typeOfPeriodicityColumn = new Column("TypeOfPeriodicity", "INTEGER", toDosTable);
            toDosTable.Columns.Add("TypeOfPeriodicity", typeOfPeriodicityColumn);
            typeOfPeriodicityColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<byte>(typeOfPeriodicityColumn);
            var weeklyDaysColumn = new Column("WeeklyDays", "TEXT", toDosTable);
            toDosTable.Columns.Add("WeeklyDays", weeklyDaysColumn);
            weeklyDaysColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(weeklyDaysColumn);
            var weeksOffsetColumn = new Column("WeeksOffset", "INTEGER", toDosTable);
            toDosTable.Columns.Add("WeeksOffset", weeksOffsetColumn);
            weeksOffsetColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<ushort>(weeksOffsetColumn);
            var yearsOffsetColumn = new Column("YearsOffset", "INTEGER", toDosTable);
            toDosTable.Columns.Add("YearsOffset", yearsOffsetColumn);
            yearsOffsetColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<ushort>(yearsOffsetColumn);
            relationalModel.Tables.Add(("ToDos", null), toDosTable);
            var toDosTableMapping = new TableMapping(toDoEntity, toDosTable, null);
            toDosTable.AddTypeMapping(toDosTableMapping, false);
            tableMappings0.Add(toDosTableMapping);
            RelationalModel.CreateColumnMapping(idColumn0, toDoEntity.FindProperty("Id")!, toDosTableMapping);
            RelationalModel.CreateColumnMapping(annuallyDaysColumn, toDoEntity.FindProperty("AnnuallyDays")!, toDosTableMapping);
            RelationalModel.CreateColumnMapping(childrenCompletionTypeColumn, toDoEntity.FindProperty("ChildrenCompletionType")!, toDosTableMapping);
            RelationalModel.CreateColumnMapping(colorColumn, toDoEntity.FindProperty("Color")!, toDosTableMapping);
            RelationalModel.CreateColumnMapping(createdDateTimeColumn, toDoEntity.FindProperty("CreatedDateTime")!, toDosTableMapping);
            RelationalModel.CreateColumnMapping(currentCircleOrderIndexColumn, toDoEntity.FindProperty("CurrentCircleOrderIndex")!, toDosTableMapping);
            RelationalModel.CreateColumnMapping(daysOffsetColumn, toDoEntity.FindProperty("DaysOffset")!, toDosTableMapping);
            RelationalModel.CreateColumnMapping(descriptionColumn, toDoEntity.FindProperty("Description")!, toDosTableMapping);
            RelationalModel.CreateColumnMapping(descriptionTypeColumn, toDoEntity.FindProperty("DescriptionType")!, toDosTableMapping);
            RelationalModel.CreateColumnMapping(dueDateColumn, toDoEntity.FindProperty("DueDate")!, toDosTableMapping);
            RelationalModel.CreateColumnMapping(iconColumn, toDoEntity.FindProperty("Icon")!, toDosTableMapping);
            RelationalModel.CreateColumnMapping(isBookmarkColumn, toDoEntity.FindProperty("IsBookmark")!, toDosTableMapping);
            RelationalModel.CreateColumnMapping(isCompletedColumn, toDoEntity.FindProperty("IsCompleted")!, toDosTableMapping);
            RelationalModel.CreateColumnMapping(isFavoriteColumn, toDoEntity.FindProperty("IsFavorite")!, toDosTableMapping);
            RelationalModel.CreateColumnMapping(isRequiredCompleteInDueDateColumn, toDoEntity.FindProperty("IsRequiredCompleteInDueDate")!, toDosTableMapping);
            RelationalModel.CreateColumnMapping(lastCompletedColumn, toDoEntity.FindProperty("LastCompleted")!, toDosTableMapping);
            RelationalModel.CreateColumnMapping(linkColumn, toDoEntity.FindProperty("Link")!, toDosTableMapping);
            RelationalModel.CreateColumnMapping(monthlyDaysColumn, toDoEntity.FindProperty("MonthlyDays")!, toDosTableMapping);
            RelationalModel.CreateColumnMapping(monthsOffsetColumn, toDoEntity.FindProperty("MonthsOffset")!, toDosTableMapping);
            RelationalModel.CreateColumnMapping(nameColumn0, toDoEntity.FindProperty("Name")!, toDosTableMapping);
            RelationalModel.CreateColumnMapping(normalizeNameColumn, toDoEntity.FindProperty("NormalizeName")!, toDosTableMapping);
            RelationalModel.CreateColumnMapping(orderIndexColumn, toDoEntity.FindProperty("OrderIndex")!, toDosTableMapping);
            RelationalModel.CreateColumnMapping(parentIdColumn, toDoEntity.FindProperty("ParentId")!, toDosTableMapping);
            RelationalModel.CreateColumnMapping(referenceIdColumn, toDoEntity.FindProperty("ReferenceId")!, toDosTableMapping);
            RelationalModel.CreateColumnMapping(remindDaysBeforeColumn, toDoEntity.FindProperty("RemindDaysBefore")!, toDosTableMapping);
            RelationalModel.CreateColumnMapping(typeColumn0, toDoEntity.FindProperty("Type")!, toDosTableMapping);
            RelationalModel.CreateColumnMapping(typeOfPeriodicityColumn, toDoEntity.FindProperty("TypeOfPeriodicity")!, toDosTableMapping);
            RelationalModel.CreateColumnMapping(weeklyDaysColumn, toDoEntity.FindProperty("WeeklyDays")!, toDosTableMapping);
            RelationalModel.CreateColumnMapping(weeksOffsetColumn, toDoEntity.FindProperty("WeeksOffset")!, toDosTableMapping);
            RelationalModel.CreateColumnMapping(yearsOffsetColumn, toDoEntity.FindProperty("YearsOffset")!, toDosTableMapping);
            var pK_ToDos = new UniqueConstraint("PK_ToDos", toDosTable, new[] { idColumn0 });
            toDosTable.PrimaryKey = pK_ToDos;
            pK_ToDos.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<Guid>(pK_ToDos));
            var pK_ToDosKey = RelationalModel.GetKey(this,
                "Hestia.Contract.Models.ToDoEntity",
                new[] { "Id" });
            pK_ToDos.MappedKeys.Add(pK_ToDosKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_ToDosKey).Add(pK_ToDos);
            toDosTable.UniqueConstraints.Add("PK_ToDos", pK_ToDos);

            var eventEntity = FindEntityType("Nestor.Db.Models.EventEntity")!;

            var defaultTableMappings1 = new List<TableMappingBase<ColumnMappingBase>>();
            eventEntity.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings1);
            var nestorDbModelsEventEntityTableBase = new TableBase("Nestor.Db.Models.EventEntity", null, relationalModel);
            var createdAtColumnBase = new ColumnBase<ColumnMappingBase>("CreatedAt", "TEXT", nestorDbModelsEventEntityTableBase);
            nestorDbModelsEventEntityTableBase.Columns.Add("CreatedAt", createdAtColumnBase);
            var entityBooleanValueColumnBase = new ColumnBase<ColumnMappingBase>("EntityBooleanValue", "INTEGER", nestorDbModelsEventEntityTableBase)
            {
                IsNullable = true
            };
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityBooleanValue", entityBooleanValueColumnBase);
            var entityByteArrayValueColumnBase = new ColumnBase<ColumnMappingBase>("EntityByteArrayValue", "BLOB", nestorDbModelsEventEntityTableBase)
            {
                IsNullable = true
            };
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityByteArrayValue", entityByteArrayValueColumnBase);
            var entityByteValueColumnBase = new ColumnBase<ColumnMappingBase>("EntityByteValue", "INTEGER", nestorDbModelsEventEntityTableBase)
            {
                IsNullable = true
            };
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityByteValue", entityByteValueColumnBase);
            var entityCharValueColumnBase = new ColumnBase<ColumnMappingBase>("EntityCharValue", "TEXT", nestorDbModelsEventEntityTableBase)
            {
                IsNullable = true
            };
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityCharValue", entityCharValueColumnBase);
            var entityDateOnlyValueColumnBase = new ColumnBase<ColumnMappingBase>("EntityDateOnlyValue", "TEXT", nestorDbModelsEventEntityTableBase)
            {
                IsNullable = true
            };
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityDateOnlyValue", entityDateOnlyValueColumnBase);
            var entityDateTimeOffsetValueColumnBase = new ColumnBase<ColumnMappingBase>("EntityDateTimeOffsetValue", "TEXT", nestorDbModelsEventEntityTableBase)
            {
                IsNullable = true
            };
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityDateTimeOffsetValue", entityDateTimeOffsetValueColumnBase);
            var entityDateTimeValueColumnBase = new ColumnBase<ColumnMappingBase>("EntityDateTimeValue", "TEXT", nestorDbModelsEventEntityTableBase)
            {
                IsNullable = true
            };
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityDateTimeValue", entityDateTimeValueColumnBase);
            var entityDecimalValueColumnBase = new ColumnBase<ColumnMappingBase>("EntityDecimalValue", "TEXT", nestorDbModelsEventEntityTableBase)
            {
                IsNullable = true
            };
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityDecimalValue", entityDecimalValueColumnBase);
            var entityDoubleValueColumnBase = new ColumnBase<ColumnMappingBase>("EntityDoubleValue", "REAL", nestorDbModelsEventEntityTableBase)
            {
                IsNullable = true
            };
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityDoubleValue", entityDoubleValueColumnBase);
            var entityGuidValueColumnBase = new ColumnBase<ColumnMappingBase>("EntityGuidValue", "TEXT", nestorDbModelsEventEntityTableBase)
            {
                IsNullable = true
            };
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityGuidValue", entityGuidValueColumnBase);
            var entityIdColumnBase = new ColumnBase<ColumnMappingBase>("EntityId", "TEXT", nestorDbModelsEventEntityTableBase);
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityId", entityIdColumnBase);
            var entityInt16ValueColumnBase = new ColumnBase<ColumnMappingBase>("EntityInt16Value", "INTEGER", nestorDbModelsEventEntityTableBase)
            {
                IsNullable = true
            };
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityInt16Value", entityInt16ValueColumnBase);
            var entityInt32ValueColumnBase = new ColumnBase<ColumnMappingBase>("EntityInt32Value", "INTEGER", nestorDbModelsEventEntityTableBase)
            {
                IsNullable = true
            };
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityInt32Value", entityInt32ValueColumnBase);
            var entityInt64ValueColumnBase = new ColumnBase<ColumnMappingBase>("EntityInt64Value", "INTEGER", nestorDbModelsEventEntityTableBase)
            {
                IsNullable = true
            };
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityInt64Value", entityInt64ValueColumnBase);
            var entityPropertyColumnBase = new ColumnBase<ColumnMappingBase>("EntityProperty", "TEXT", nestorDbModelsEventEntityTableBase);
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityProperty", entityPropertyColumnBase);
            var entitySByteValueColumnBase = new ColumnBase<ColumnMappingBase>("EntitySByteValue", "INTEGER", nestorDbModelsEventEntityTableBase)
            {
                IsNullable = true
            };
            nestorDbModelsEventEntityTableBase.Columns.Add("EntitySByteValue", entitySByteValueColumnBase);
            var entitySingleValueColumnBase = new ColumnBase<ColumnMappingBase>("EntitySingleValue", "REAL", nestorDbModelsEventEntityTableBase)
            {
                IsNullable = true
            };
            nestorDbModelsEventEntityTableBase.Columns.Add("EntitySingleValue", entitySingleValueColumnBase);
            var entityStringValueColumnBase = new ColumnBase<ColumnMappingBase>("EntityStringValue", "TEXT", nestorDbModelsEventEntityTableBase)
            {
                IsNullable = true
            };
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityStringValue", entityStringValueColumnBase);
            var entityTimeOnlyValueColumnBase = new ColumnBase<ColumnMappingBase>("EntityTimeOnlyValue", "TEXT", nestorDbModelsEventEntityTableBase)
            {
                IsNullable = true
            };
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityTimeOnlyValue", entityTimeOnlyValueColumnBase);
            var entityTimeSpanValueColumnBase = new ColumnBase<ColumnMappingBase>("EntityTimeSpanValue", "TEXT", nestorDbModelsEventEntityTableBase)
            {
                IsNullable = true
            };
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityTimeSpanValue", entityTimeSpanValueColumnBase);
            var entityTypeColumnBase = new ColumnBase<ColumnMappingBase>("EntityType", "TEXT", nestorDbModelsEventEntityTableBase);
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityType", entityTypeColumnBase);
            var entityUInt16ValueColumnBase = new ColumnBase<ColumnMappingBase>("EntityUInt16Value", "INTEGER", nestorDbModelsEventEntityTableBase)
            {
                IsNullable = true
            };
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityUInt16Value", entityUInt16ValueColumnBase);
            var entityUInt32ValueColumnBase = new ColumnBase<ColumnMappingBase>("EntityUInt32Value", "INTEGER", nestorDbModelsEventEntityTableBase)
            {
                IsNullable = true
            };
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityUInt32Value", entityUInt32ValueColumnBase);
            var entityUInt64ValueColumnBase = new ColumnBase<ColumnMappingBase>("EntityUInt64Value", "INTEGER", nestorDbModelsEventEntityTableBase)
            {
                IsNullable = true
            };
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityUInt64Value", entityUInt64ValueColumnBase);
            var idColumnBase1 = new ColumnBase<ColumnMappingBase>("Id", "INTEGER", nestorDbModelsEventEntityTableBase);
            nestorDbModelsEventEntityTableBase.Columns.Add("Id", idColumnBase1);
            var transactionIdColumnBase = new ColumnBase<ColumnMappingBase>("TransactionId", "TEXT", nestorDbModelsEventEntityTableBase);
            nestorDbModelsEventEntityTableBase.Columns.Add("TransactionId", transactionIdColumnBase);
            var userIdColumnBase = new ColumnBase<ColumnMappingBase>("UserId", "TEXT", nestorDbModelsEventEntityTableBase);
            nestorDbModelsEventEntityTableBase.Columns.Add("UserId", userIdColumnBase);
            relationalModel.DefaultTables.Add("Nestor.Db.Models.EventEntity", nestorDbModelsEventEntityTableBase);
            var nestorDbModelsEventEntityMappingBase = new TableMappingBase<ColumnMappingBase>(eventEntity, nestorDbModelsEventEntityTableBase, null);
            nestorDbModelsEventEntityTableBase.AddTypeMapping(nestorDbModelsEventEntityMappingBase, false);
            defaultTableMappings1.Add(nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase1, eventEntity.FindProperty("Id")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)createdAtColumnBase, eventEntity.FindProperty("CreatedAt")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityBooleanValueColumnBase, eventEntity.FindProperty("EntityBooleanValue")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityByteArrayValueColumnBase, eventEntity.FindProperty("EntityByteArrayValue")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityByteValueColumnBase, eventEntity.FindProperty("EntityByteValue")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityCharValueColumnBase, eventEntity.FindProperty("EntityCharValue")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityDateOnlyValueColumnBase, eventEntity.FindProperty("EntityDateOnlyValue")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityDateTimeOffsetValueColumnBase, eventEntity.FindProperty("EntityDateTimeOffsetValue")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityDateTimeValueColumnBase, eventEntity.FindProperty("EntityDateTimeValue")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityDecimalValueColumnBase, eventEntity.FindProperty("EntityDecimalValue")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityDoubleValueColumnBase, eventEntity.FindProperty("EntityDoubleValue")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityGuidValueColumnBase, eventEntity.FindProperty("EntityGuidValue")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityIdColumnBase, eventEntity.FindProperty("EntityId")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityInt16ValueColumnBase, eventEntity.FindProperty("EntityInt16Value")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityInt32ValueColumnBase, eventEntity.FindProperty("EntityInt32Value")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityInt64ValueColumnBase, eventEntity.FindProperty("EntityInt64Value")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityPropertyColumnBase, eventEntity.FindProperty("EntityProperty")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entitySByteValueColumnBase, eventEntity.FindProperty("EntitySByteValue")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entitySingleValueColumnBase, eventEntity.FindProperty("EntitySingleValue")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityStringValueColumnBase, eventEntity.FindProperty("EntityStringValue")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityTimeOnlyValueColumnBase, eventEntity.FindProperty("EntityTimeOnlyValue")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityTimeSpanValueColumnBase, eventEntity.FindProperty("EntityTimeSpanValue")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityTypeColumnBase, eventEntity.FindProperty("EntityType")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityUInt16ValueColumnBase, eventEntity.FindProperty("EntityUInt16Value")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityUInt32ValueColumnBase, eventEntity.FindProperty("EntityUInt32Value")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityUInt64ValueColumnBase, eventEntity.FindProperty("EntityUInt64Value")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)transactionIdColumnBase, eventEntity.FindProperty("TransactionId")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)userIdColumnBase, eventEntity.FindProperty("UserId")!, nestorDbModelsEventEntityMappingBase);

            var tableMappings1 = new List<TableMapping>();
            eventEntity.SetRuntimeAnnotation("Relational:TableMappings", tableMappings1);
            var eventsTable = new Table("Events", null, relationalModel);
            var idColumn1 = new Column("Id", "INTEGER", eventsTable);
            eventsTable.Columns.Add("Id", idColumn1);
            idColumn1.Accessors = ColumnAccessorsFactory.CreateGeneric<long>(idColumn1);
            var createdAtColumn = new Column("CreatedAt", "TEXT", eventsTable);
            eventsTable.Columns.Add("CreatedAt", createdAtColumn);
            createdAtColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTimeOffset>(createdAtColumn);
            var entityBooleanValueColumn = new Column("EntityBooleanValue", "INTEGER", eventsTable)
            {
                IsNullable = true
            };
            eventsTable.Columns.Add("EntityBooleanValue", entityBooleanValueColumn);
            entityBooleanValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<bool>(entityBooleanValueColumn);
            var entityByteArrayValueColumn = new Column("EntityByteArrayValue", "BLOB", eventsTable)
            {
                IsNullable = true
            };
            eventsTable.Columns.Add("EntityByteArrayValue", entityByteArrayValueColumn);
            entityByteArrayValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<byte[]>(entityByteArrayValueColumn);
            var entityByteValueColumn = new Column("EntityByteValue", "INTEGER", eventsTable)
            {
                IsNullable = true
            };
            eventsTable.Columns.Add("EntityByteValue", entityByteValueColumn);
            entityByteValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<byte>(entityByteValueColumn);
            var entityCharValueColumn = new Column("EntityCharValue", "TEXT", eventsTable)
            {
                IsNullable = true
            };
            eventsTable.Columns.Add("EntityCharValue", entityCharValueColumn);
            entityCharValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<char>(entityCharValueColumn);
            var entityDateOnlyValueColumn = new Column("EntityDateOnlyValue", "TEXT", eventsTable)
            {
                IsNullable = true
            };
            eventsTable.Columns.Add("EntityDateOnlyValue", entityDateOnlyValueColumn);
            entityDateOnlyValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<DateOnly>(entityDateOnlyValueColumn);
            var entityDateTimeOffsetValueColumn = new Column("EntityDateTimeOffsetValue", "TEXT", eventsTable)
            {
                IsNullable = true
            };
            eventsTable.Columns.Add("EntityDateTimeOffsetValue", entityDateTimeOffsetValueColumn);
            entityDateTimeOffsetValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTimeOffset>(entityDateTimeOffsetValueColumn);
            var entityDateTimeValueColumn = new Column("EntityDateTimeValue", "TEXT", eventsTable)
            {
                IsNullable = true
            };
            eventsTable.Columns.Add("EntityDateTimeValue", entityDateTimeValueColumn);
            entityDateTimeValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTime>(entityDateTimeValueColumn);
            var entityDecimalValueColumn = new Column("EntityDecimalValue", "TEXT", eventsTable)
            {
                IsNullable = true
            };
            eventsTable.Columns.Add("EntityDecimalValue", entityDecimalValueColumn);
            entityDecimalValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<decimal>(entityDecimalValueColumn);
            var entityDoubleValueColumn = new Column("EntityDoubleValue", "REAL", eventsTable)
            {
                IsNullable = true
            };
            eventsTable.Columns.Add("EntityDoubleValue", entityDoubleValueColumn);
            entityDoubleValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<double>(entityDoubleValueColumn);
            var entityGuidValueColumn = new Column("EntityGuidValue", "TEXT", eventsTable)
            {
                IsNullable = true
            };
            eventsTable.Columns.Add("EntityGuidValue", entityGuidValueColumn);
            entityGuidValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(entityGuidValueColumn);
            var entityIdColumn = new Column("EntityId", "TEXT", eventsTable);
            eventsTable.Columns.Add("EntityId", entityIdColumn);
            entityIdColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(entityIdColumn);
            var entityInt16ValueColumn = new Column("EntityInt16Value", "INTEGER", eventsTable)
            {
                IsNullable = true
            };
            eventsTable.Columns.Add("EntityInt16Value", entityInt16ValueColumn);
            entityInt16ValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<short>(entityInt16ValueColumn);
            var entityInt32ValueColumn = new Column("EntityInt32Value", "INTEGER", eventsTable)
            {
                IsNullable = true
            };
            eventsTable.Columns.Add("EntityInt32Value", entityInt32ValueColumn);
            entityInt32ValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(entityInt32ValueColumn);
            var entityInt64ValueColumn = new Column("EntityInt64Value", "INTEGER", eventsTable)
            {
                IsNullable = true
            };
            eventsTable.Columns.Add("EntityInt64Value", entityInt64ValueColumn);
            entityInt64ValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<long>(entityInt64ValueColumn);
            var entityPropertyColumn = new Column("EntityProperty", "TEXT", eventsTable);
            eventsTable.Columns.Add("EntityProperty", entityPropertyColumn);
            entityPropertyColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(entityPropertyColumn);
            var entitySByteValueColumn = new Column("EntitySByteValue", "INTEGER", eventsTable)
            {
                IsNullable = true
            };
            eventsTable.Columns.Add("EntitySByteValue", entitySByteValueColumn);
            entitySByteValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<sbyte>(entitySByteValueColumn);
            var entitySingleValueColumn = new Column("EntitySingleValue", "REAL", eventsTable)
            {
                IsNullable = true
            };
            eventsTable.Columns.Add("EntitySingleValue", entitySingleValueColumn);
            entitySingleValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<float>(entitySingleValueColumn);
            var entityStringValueColumn = new Column("EntityStringValue", "TEXT", eventsTable)
            {
                IsNullable = true
            };
            eventsTable.Columns.Add("EntityStringValue", entityStringValueColumn);
            entityStringValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(entityStringValueColumn);
            var entityTimeOnlyValueColumn = new Column("EntityTimeOnlyValue", "TEXT", eventsTable)
            {
                IsNullable = true
            };
            eventsTable.Columns.Add("EntityTimeOnlyValue", entityTimeOnlyValueColumn);
            entityTimeOnlyValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<TimeOnly>(entityTimeOnlyValueColumn);
            var entityTimeSpanValueColumn = new Column("EntityTimeSpanValue", "TEXT", eventsTable)
            {
                IsNullable = true
            };
            eventsTable.Columns.Add("EntityTimeSpanValue", entityTimeSpanValueColumn);
            entityTimeSpanValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<TimeSpan>(entityTimeSpanValueColumn);
            var entityTypeColumn = new Column("EntityType", "TEXT", eventsTable);
            eventsTable.Columns.Add("EntityType", entityTypeColumn);
            entityTypeColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(entityTypeColumn);
            var entityUInt16ValueColumn = new Column("EntityUInt16Value", "INTEGER", eventsTable)
            {
                IsNullable = true
            };
            eventsTable.Columns.Add("EntityUInt16Value", entityUInt16ValueColumn);
            entityUInt16ValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<ushort>(entityUInt16ValueColumn);
            var entityUInt32ValueColumn = new Column("EntityUInt32Value", "INTEGER", eventsTable)
            {
                IsNullable = true
            };
            eventsTable.Columns.Add("EntityUInt32Value", entityUInt32ValueColumn);
            entityUInt32ValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<uint>(entityUInt32ValueColumn);
            var entityUInt64ValueColumn = new Column("EntityUInt64Value", "INTEGER", eventsTable)
            {
                IsNullable = true
            };
            eventsTable.Columns.Add("EntityUInt64Value", entityUInt64ValueColumn);
            entityUInt64ValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<ulong>(entityUInt64ValueColumn);
            var transactionIdColumn = new Column("TransactionId", "TEXT", eventsTable);
            eventsTable.Columns.Add("TransactionId", transactionIdColumn);
            transactionIdColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(transactionIdColumn);
            var userIdColumn = new Column("UserId", "TEXT", eventsTable);
            eventsTable.Columns.Add("UserId", userIdColumn);
            userIdColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(userIdColumn);
            relationalModel.Tables.Add(("Events", null), eventsTable);
            var eventsTableMapping = new TableMapping(eventEntity, eventsTable, null);
            eventsTable.AddTypeMapping(eventsTableMapping, false);
            tableMappings1.Add(eventsTableMapping);
            RelationalModel.CreateColumnMapping(idColumn1, eventEntity.FindProperty("Id")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(createdAtColumn, eventEntity.FindProperty("CreatedAt")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityBooleanValueColumn, eventEntity.FindProperty("EntityBooleanValue")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityByteArrayValueColumn, eventEntity.FindProperty("EntityByteArrayValue")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityByteValueColumn, eventEntity.FindProperty("EntityByteValue")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityCharValueColumn, eventEntity.FindProperty("EntityCharValue")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityDateOnlyValueColumn, eventEntity.FindProperty("EntityDateOnlyValue")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityDateTimeOffsetValueColumn, eventEntity.FindProperty("EntityDateTimeOffsetValue")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityDateTimeValueColumn, eventEntity.FindProperty("EntityDateTimeValue")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityDecimalValueColumn, eventEntity.FindProperty("EntityDecimalValue")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityDoubleValueColumn, eventEntity.FindProperty("EntityDoubleValue")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityGuidValueColumn, eventEntity.FindProperty("EntityGuidValue")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityIdColumn, eventEntity.FindProperty("EntityId")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityInt16ValueColumn, eventEntity.FindProperty("EntityInt16Value")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityInt32ValueColumn, eventEntity.FindProperty("EntityInt32Value")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityInt64ValueColumn, eventEntity.FindProperty("EntityInt64Value")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityPropertyColumn, eventEntity.FindProperty("EntityProperty")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entitySByteValueColumn, eventEntity.FindProperty("EntitySByteValue")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entitySingleValueColumn, eventEntity.FindProperty("EntitySingleValue")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityStringValueColumn, eventEntity.FindProperty("EntityStringValue")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityTimeOnlyValueColumn, eventEntity.FindProperty("EntityTimeOnlyValue")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityTimeSpanValueColumn, eventEntity.FindProperty("EntityTimeSpanValue")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityTypeColumn, eventEntity.FindProperty("EntityType")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityUInt16ValueColumn, eventEntity.FindProperty("EntityUInt16Value")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityUInt32ValueColumn, eventEntity.FindProperty("EntityUInt32Value")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityUInt64ValueColumn, eventEntity.FindProperty("EntityUInt64Value")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(transactionIdColumn, eventEntity.FindProperty("TransactionId")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(userIdColumn, eventEntity.FindProperty("UserId")!, eventsTableMapping);
            var pK_Events = new UniqueConstraint("PK_Events", eventsTable, new[] { idColumn1 });
            eventsTable.PrimaryKey = pK_Events;
            pK_Events.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<long>(pK_Events));
            var pK_EventsKey = RelationalModel.GetKey(this,
                "Nestor.Db.Models.EventEntity",
                new[] { "Id" });
            pK_Events.MappedKeys.Add(pK_EventsKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_EventsKey).Add(pK_Events);
            eventsTable.UniqueConstraints.Add("PK_Events", pK_Events);

            var migrationEntity = FindEntityType("Nestor.Db.Models.MigrationEntity")!;

            var defaultTableMappings2 = new List<TableMappingBase<ColumnMappingBase>>();
            migrationEntity.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings2);
            var nestorDbModelsMigrationEntityTableBase = new TableBase("Nestor.Db.Models.MigrationEntity", null, relationalModel);
            var idColumnBase2 = new ColumnBase<ColumnMappingBase>("Id", "INTEGER", nestorDbModelsMigrationEntityTableBase);
            nestorDbModelsMigrationEntityTableBase.Columns.Add("Id", idColumnBase2);
            var sqlColumnBase = new ColumnBase<ColumnMappingBase>("Sql", "TEXT", nestorDbModelsMigrationEntityTableBase);
            nestorDbModelsMigrationEntityTableBase.Columns.Add("Sql", sqlColumnBase);
            relationalModel.DefaultTables.Add("Nestor.Db.Models.MigrationEntity", nestorDbModelsMigrationEntityTableBase);
            var nestorDbModelsMigrationEntityMappingBase = new TableMappingBase<ColumnMappingBase>(migrationEntity, nestorDbModelsMigrationEntityTableBase, null);
            nestorDbModelsMigrationEntityTableBase.AddTypeMapping(nestorDbModelsMigrationEntityMappingBase, false);
            defaultTableMappings2.Add(nestorDbModelsMigrationEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase2, migrationEntity.FindProperty("Id")!, nestorDbModelsMigrationEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)sqlColumnBase, migrationEntity.FindProperty("Sql")!, nestorDbModelsMigrationEntityMappingBase);

            var tableMappings2 = new List<TableMapping>();
            migrationEntity.SetRuntimeAnnotation("Relational:TableMappings", tableMappings2);
            var migrationsTable = new Table("Migrations", null, relationalModel);
            var idColumn2 = new Column("Id", "INTEGER", migrationsTable);
            migrationsTable.Columns.Add("Id", idColumn2);
            idColumn2.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(idColumn2);
            var sqlColumn = new Column("Sql", "TEXT", migrationsTable);
            migrationsTable.Columns.Add("Sql", sqlColumn);
            sqlColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(sqlColumn);
            relationalModel.Tables.Add(("Migrations", null), migrationsTable);
            var migrationsTableMapping = new TableMapping(migrationEntity, migrationsTable, null);
            migrationsTable.AddTypeMapping(migrationsTableMapping, false);
            tableMappings2.Add(migrationsTableMapping);
            RelationalModel.CreateColumnMapping(idColumn2, migrationEntity.FindProperty("Id")!, migrationsTableMapping);
            RelationalModel.CreateColumnMapping(sqlColumn, migrationEntity.FindProperty("Sql")!, migrationsTableMapping);
            var pK_Migrations = new UniqueConstraint("PK_Migrations", migrationsTable, new[] { idColumn2 });
            migrationsTable.PrimaryKey = pK_Migrations;
            pK_Migrations.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<int>(pK_Migrations));
            var pK_MigrationsKey = RelationalModel.GetKey(this,
                "Nestor.Db.Models.MigrationEntity",
                new[] { "Id" });
            pK_Migrations.MappedKeys.Add(pK_MigrationsKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_MigrationsKey).Add(pK_Migrations);
            migrationsTable.UniqueConstraints.Add("PK_Migrations", pK_Migrations);

            var credentialEntity = FindEntityType("Turtle.Contract.Models.CredentialEntity")!;

            var defaultTableMappings3 = new List<TableMappingBase<ColumnMappingBase>>();
            credentialEntity.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings3);
            var turtleContractModelsCredentialEntityTableBase = new TableBase("Turtle.Contract.Models.CredentialEntity", null, relationalModel);
            var customAvailableCharactersColumnBase = new ColumnBase<ColumnMappingBase>("CustomAvailableCharacters", "TEXT", turtleContractModelsCredentialEntityTableBase);
            turtleContractModelsCredentialEntityTableBase.Columns.Add("CustomAvailableCharacters", customAvailableCharactersColumnBase);
            var idColumnBase3 = new ColumnBase<ColumnMappingBase>("Id", "TEXT", turtleContractModelsCredentialEntityTableBase);
            turtleContractModelsCredentialEntityTableBase.Columns.Add("Id", idColumnBase3);
            var isAvailableLowerLatinColumnBase = new ColumnBase<ColumnMappingBase>("IsAvailableLowerLatin", "INTEGER", turtleContractModelsCredentialEntityTableBase);
            turtleContractModelsCredentialEntityTableBase.Columns.Add("IsAvailableLowerLatin", isAvailableLowerLatinColumnBase);
            var isAvailableNumberColumnBase = new ColumnBase<ColumnMappingBase>("IsAvailableNumber", "INTEGER", turtleContractModelsCredentialEntityTableBase);
            turtleContractModelsCredentialEntityTableBase.Columns.Add("IsAvailableNumber", isAvailableNumberColumnBase);
            var isAvailableSpecialSymbolsColumnBase = new ColumnBase<ColumnMappingBase>("IsAvailableSpecialSymbols", "INTEGER", turtleContractModelsCredentialEntityTableBase);
            turtleContractModelsCredentialEntityTableBase.Columns.Add("IsAvailableSpecialSymbols", isAvailableSpecialSymbolsColumnBase);
            var isAvailableUpperLatinColumnBase = new ColumnBase<ColumnMappingBase>("IsAvailableUpperLatin", "INTEGER", turtleContractModelsCredentialEntityTableBase);
            turtleContractModelsCredentialEntityTableBase.Columns.Add("IsAvailableUpperLatin", isAvailableUpperLatinColumnBase);
            var keyColumnBase = new ColumnBase<ColumnMappingBase>("Key", "TEXT", turtleContractModelsCredentialEntityTableBase);
            turtleContractModelsCredentialEntityTableBase.Columns.Add("Key", keyColumnBase);
            var lengthColumnBase = new ColumnBase<ColumnMappingBase>("Length", "INTEGER", turtleContractModelsCredentialEntityTableBase);
            turtleContractModelsCredentialEntityTableBase.Columns.Add("Length", lengthColumnBase);
            var loginColumnBase0 = new ColumnBase<ColumnMappingBase>("Login", "TEXT", turtleContractModelsCredentialEntityTableBase);
            turtleContractModelsCredentialEntityTableBase.Columns.Add("Login", loginColumnBase0);
            var nameColumnBase1 = new ColumnBase<ColumnMappingBase>("Name", "TEXT", turtleContractModelsCredentialEntityTableBase);
            turtleContractModelsCredentialEntityTableBase.Columns.Add("Name", nameColumnBase1);
            var orderIndexColumnBase0 = new ColumnBase<ColumnMappingBase>("OrderIndex", "INTEGER", turtleContractModelsCredentialEntityTableBase);
            turtleContractModelsCredentialEntityTableBase.Columns.Add("OrderIndex", orderIndexColumnBase0);
            var parentIdColumnBase0 = new ColumnBase<ColumnMappingBase>("ParentId", "TEXT", turtleContractModelsCredentialEntityTableBase)
            {
                IsNullable = true
            };
            turtleContractModelsCredentialEntityTableBase.Columns.Add("ParentId", parentIdColumnBase0);
            var regexColumnBase = new ColumnBase<ColumnMappingBase>("Regex", "TEXT", turtleContractModelsCredentialEntityTableBase);
            turtleContractModelsCredentialEntityTableBase.Columns.Add("Regex", regexColumnBase);
            var typeColumnBase1 = new ColumnBase<ColumnMappingBase>("Type", "INTEGER", turtleContractModelsCredentialEntityTableBase);
            turtleContractModelsCredentialEntityTableBase.Columns.Add("Type", typeColumnBase1);
            relationalModel.DefaultTables.Add("Turtle.Contract.Models.CredentialEntity", turtleContractModelsCredentialEntityTableBase);
            var turtleContractModelsCredentialEntityMappingBase = new TableMappingBase<ColumnMappingBase>(credentialEntity, turtleContractModelsCredentialEntityTableBase, null);
            turtleContractModelsCredentialEntityTableBase.AddTypeMapping(turtleContractModelsCredentialEntityMappingBase, false);
            defaultTableMappings3.Add(turtleContractModelsCredentialEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase3, credentialEntity.FindProperty("Id")!, turtleContractModelsCredentialEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)customAvailableCharactersColumnBase, credentialEntity.FindProperty("CustomAvailableCharacters")!, turtleContractModelsCredentialEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)isAvailableLowerLatinColumnBase, credentialEntity.FindProperty("IsAvailableLowerLatin")!, turtleContractModelsCredentialEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)isAvailableNumberColumnBase, credentialEntity.FindProperty("IsAvailableNumber")!, turtleContractModelsCredentialEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)isAvailableSpecialSymbolsColumnBase, credentialEntity.FindProperty("IsAvailableSpecialSymbols")!, turtleContractModelsCredentialEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)isAvailableUpperLatinColumnBase, credentialEntity.FindProperty("IsAvailableUpperLatin")!, turtleContractModelsCredentialEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)keyColumnBase, credentialEntity.FindProperty("Key")!, turtleContractModelsCredentialEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)lengthColumnBase, credentialEntity.FindProperty("Length")!, turtleContractModelsCredentialEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)loginColumnBase0, credentialEntity.FindProperty("Login")!, turtleContractModelsCredentialEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nameColumnBase1, credentialEntity.FindProperty("Name")!, turtleContractModelsCredentialEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)orderIndexColumnBase0, credentialEntity.FindProperty("OrderIndex")!, turtleContractModelsCredentialEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)parentIdColumnBase0, credentialEntity.FindProperty("ParentId")!, turtleContractModelsCredentialEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)regexColumnBase, credentialEntity.FindProperty("Regex")!, turtleContractModelsCredentialEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)typeColumnBase1, credentialEntity.FindProperty("Type")!, turtleContractModelsCredentialEntityMappingBase);

            var tableMappings3 = new List<TableMapping>();
            credentialEntity.SetRuntimeAnnotation("Relational:TableMappings", tableMappings3);
            var credentialsTable = new Table("Credentials", null, relationalModel);
            var idColumn3 = new Column("Id", "TEXT", credentialsTable);
            credentialsTable.Columns.Add("Id", idColumn3);
            idColumn3.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(idColumn3);
            var customAvailableCharactersColumn = new Column("CustomAvailableCharacters", "TEXT", credentialsTable);
            credentialsTable.Columns.Add("CustomAvailableCharacters", customAvailableCharactersColumn);
            customAvailableCharactersColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(customAvailableCharactersColumn);
            var isAvailableLowerLatinColumn = new Column("IsAvailableLowerLatin", "INTEGER", credentialsTable);
            credentialsTable.Columns.Add("IsAvailableLowerLatin", isAvailableLowerLatinColumn);
            isAvailableLowerLatinColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<bool>(isAvailableLowerLatinColumn);
            var isAvailableNumberColumn = new Column("IsAvailableNumber", "INTEGER", credentialsTable);
            credentialsTable.Columns.Add("IsAvailableNumber", isAvailableNumberColumn);
            isAvailableNumberColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<bool>(isAvailableNumberColumn);
            var isAvailableSpecialSymbolsColumn = new Column("IsAvailableSpecialSymbols", "INTEGER", credentialsTable);
            credentialsTable.Columns.Add("IsAvailableSpecialSymbols", isAvailableSpecialSymbolsColumn);
            isAvailableSpecialSymbolsColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<bool>(isAvailableSpecialSymbolsColumn);
            var isAvailableUpperLatinColumn = new Column("IsAvailableUpperLatin", "INTEGER", credentialsTable);
            credentialsTable.Columns.Add("IsAvailableUpperLatin", isAvailableUpperLatinColumn);
            isAvailableUpperLatinColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<bool>(isAvailableUpperLatinColumn);
            var keyColumn = new Column("Key", "TEXT", credentialsTable);
            credentialsTable.Columns.Add("Key", keyColumn);
            keyColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(keyColumn);
            var lengthColumn = new Column("Length", "INTEGER", credentialsTable);
            credentialsTable.Columns.Add("Length", lengthColumn);
            lengthColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<ushort>(lengthColumn);
            var loginColumn0 = new Column("Login", "TEXT", credentialsTable);
            credentialsTable.Columns.Add("Login", loginColumn0);
            loginColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(loginColumn0);
            var nameColumn1 = new Column("Name", "TEXT", credentialsTable);
            credentialsTable.Columns.Add("Name", nameColumn1);
            nameColumn1.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(nameColumn1);
            var orderIndexColumn0 = new Column("OrderIndex", "INTEGER", credentialsTable);
            credentialsTable.Columns.Add("OrderIndex", orderIndexColumn0);
            orderIndexColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<uint>(orderIndexColumn0);
            var parentIdColumn0 = new Column("ParentId", "TEXT", credentialsTable)
            {
                IsNullable = true
            };
            credentialsTable.Columns.Add("ParentId", parentIdColumn0);
            parentIdColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(parentIdColumn0);
            var regexColumn = new Column("Regex", "TEXT", credentialsTable);
            credentialsTable.Columns.Add("Regex", regexColumn);
            regexColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(regexColumn);
            var typeColumn1 = new Column("Type", "INTEGER", credentialsTable);
            credentialsTable.Columns.Add("Type", typeColumn1);
            typeColumn1.Accessors = ColumnAccessorsFactory.CreateGeneric<byte>(typeColumn1);
            relationalModel.Tables.Add(("Credentials", null), credentialsTable);
            var credentialsTableMapping = new TableMapping(credentialEntity, credentialsTable, null);
            credentialsTable.AddTypeMapping(credentialsTableMapping, false);
            tableMappings3.Add(credentialsTableMapping);
            RelationalModel.CreateColumnMapping(idColumn3, credentialEntity.FindProperty("Id")!, credentialsTableMapping);
            RelationalModel.CreateColumnMapping(customAvailableCharactersColumn, credentialEntity.FindProperty("CustomAvailableCharacters")!, credentialsTableMapping);
            RelationalModel.CreateColumnMapping(isAvailableLowerLatinColumn, credentialEntity.FindProperty("IsAvailableLowerLatin")!, credentialsTableMapping);
            RelationalModel.CreateColumnMapping(isAvailableNumberColumn, credentialEntity.FindProperty("IsAvailableNumber")!, credentialsTableMapping);
            RelationalModel.CreateColumnMapping(isAvailableSpecialSymbolsColumn, credentialEntity.FindProperty("IsAvailableSpecialSymbols")!, credentialsTableMapping);
            RelationalModel.CreateColumnMapping(isAvailableUpperLatinColumn, credentialEntity.FindProperty("IsAvailableUpperLatin")!, credentialsTableMapping);
            RelationalModel.CreateColumnMapping(keyColumn, credentialEntity.FindProperty("Key")!, credentialsTableMapping);
            RelationalModel.CreateColumnMapping(lengthColumn, credentialEntity.FindProperty("Length")!, credentialsTableMapping);
            RelationalModel.CreateColumnMapping(loginColumn0, credentialEntity.FindProperty("Login")!, credentialsTableMapping);
            RelationalModel.CreateColumnMapping(nameColumn1, credentialEntity.FindProperty("Name")!, credentialsTableMapping);
            RelationalModel.CreateColumnMapping(orderIndexColumn0, credentialEntity.FindProperty("OrderIndex")!, credentialsTableMapping);
            RelationalModel.CreateColumnMapping(parentIdColumn0, credentialEntity.FindProperty("ParentId")!, credentialsTableMapping);
            RelationalModel.CreateColumnMapping(regexColumn, credentialEntity.FindProperty("Regex")!, credentialsTableMapping);
            RelationalModel.CreateColumnMapping(typeColumn1, credentialEntity.FindProperty("Type")!, credentialsTableMapping);
            var pK_Credentials = new UniqueConstraint("PK_Credentials", credentialsTable, new[] { idColumn3 });
            credentialsTable.PrimaryKey = pK_Credentials;
            pK_Credentials.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<Guid>(pK_Credentials));
            var pK_CredentialsKey = RelationalModel.GetKey(this,
                "Turtle.Contract.Models.CredentialEntity",
                new[] { "Id" });
            pK_Credentials.MappedKeys.Add(pK_CredentialsKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_CredentialsKey).Add(pK_Credentials);
            credentialsTable.UniqueConstraints.Add("PK_Credentials", pK_Credentials);
            return relationalModel.MakeReadOnly();
        }
    }
}
