// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Sprava
{
    public partial class SpravaDbContextModel
    {
        private SpravaDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("a503dc15-842e-4c8d-b8d8-d5e759960b53"), entityTypeCount: 3)
        {
        }

        partial void Initialize()
        {
            var fileEntity = FileEntityEntityType.Create(this);
            var eventEntity = EventEntityEntityType.Create(this);
            var migrationEntity = MigrationEntityEntityType.Create(this);

            FileEntityEntityType.CreateAnnotations(fileEntity);
            EventEntityEntityType.CreateAnnotations(eventEntity);
            MigrationEntityEntityType.CreateAnnotations(migrationEntity);

            AddAnnotation("ProductVersion", "10.0.1");
        }
    }
}
