// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Sprava.CompiledModels;
using Sprava.Services;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(SpravaDbContext), typeof(SpravaDbContextModel))]
