// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Hestia.Contract.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Sprava.CompiledModels
{
    public static class ToDoEntityUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref Guid Id(ToDoEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<AnnuallyDays>k__BackingField")]
        public static extern ref string AnnuallyDays(ToDoEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ChildrenCompletionType>k__BackingField")]
        public static extern ref ChildrenCompletionType ChildrenCompletionType(ToDoEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Color>k__BackingField")]
        public static extern ref string Color(ToDoEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedDateTime>k__BackingField")]
        public static extern ref DateTimeOffset CreatedDateTime(ToDoEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CurrentCircleOrderIndex>k__BackingField")]
        public static extern ref uint CurrentCircleOrderIndex(ToDoEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<DaysOffset>k__BackingField")]
        public static extern ref ushort DaysOffset(ToDoEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Description>k__BackingField")]
        public static extern ref string Description(ToDoEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<DescriptionType>k__BackingField")]
        public static extern ref DescriptionType DescriptionType(ToDoEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<DueDate>k__BackingField")]
        public static extern ref DateOnly DueDate(ToDoEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Icon>k__BackingField")]
        public static extern ref string Icon(ToDoEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsBookmark>k__BackingField")]
        public static extern ref bool IsBookmark(ToDoEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsCompleted>k__BackingField")]
        public static extern ref bool IsCompleted(ToDoEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsFavorite>k__BackingField")]
        public static extern ref bool IsFavorite(ToDoEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsRequiredCompleteInDueDate>k__BackingField")]
        public static extern ref bool IsRequiredCompleteInDueDate(ToDoEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LastCompleted>k__BackingField")]
        public static extern ref DateTimeOffset? LastCompleted(ToDoEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Link>k__BackingField")]
        public static extern ref string Link(ToDoEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MonthlyDays>k__BackingField")]
        public static extern ref string MonthlyDays(ToDoEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MonthsOffset>k__BackingField")]
        public static extern ref ushort MonthsOffset(ToDoEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
        public static extern ref string Name(ToDoEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<NormalizeName>k__BackingField")]
        public static extern ref string NormalizeName(ToDoEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<OrderIndex>k__BackingField")]
        public static extern ref uint OrderIndex(ToDoEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ParentId>k__BackingField")]
        public static extern ref Guid? ParentId(ToDoEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ReferenceId>k__BackingField")]
        public static extern ref Guid? ReferenceId(ToDoEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<RemindDaysBefore>k__BackingField")]
        public static extern ref uint RemindDaysBefore(ToDoEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Type>k__BackingField")]
        public static extern ref ToDoType Type(ToDoEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TypeOfPeriodicity>k__BackingField")]
        public static extern ref TypeOfPeriodicity TypeOfPeriodicity(ToDoEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<WeeklyDays>k__BackingField")]
        public static extern ref string WeeklyDays(ToDoEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<WeeksOffset>k__BackingField")]
        public static extern ref ushort WeeksOffset(ToDoEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<YearsOffset>k__BackingField")]
        public static extern ref ushort YearsOffset(ToDoEntity @this);
    }
}
