// <auto-generated />
using System;
using System.Reflection;
using Hestia.Contract.Models;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Sprava.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class ToDoEntityEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Hestia.Contract.Models.ToDoEntity",
                typeof(ToDoEntity),
                baseEntityType,
                propertyCount: 30,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(ToDoEntity).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ToDoEntity).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));

            var annuallyDays = runtimeEntityType.AddProperty(
                "AnnuallyDays",
                typeof(string),
                propertyInfo: typeof(ToDoEntity).GetProperty("AnnuallyDays", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ToDoEntity).GetField("<AnnuallyDays>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var childrenCompletionType = runtimeEntityType.AddProperty(
                "ChildrenCompletionType",
                typeof(ChildrenCompletionType),
                propertyInfo: typeof(ToDoEntity).GetProperty("ChildrenCompletionType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ToDoEntity).GetField("<ChildrenCompletionType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            childrenCompletionType.SetSentinelFromProviderValue((byte)0);

            var color = runtimeEntityType.AddProperty(
                "Color",
                typeof(string),
                propertyInfo: typeof(ToDoEntity).GetProperty("Color", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ToDoEntity).GetField("<Color>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var createdDateTime = runtimeEntityType.AddProperty(
                "CreatedDateTime",
                typeof(DateTimeOffset),
                propertyInfo: typeof(ToDoEntity).GetProperty("CreatedDateTime", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ToDoEntity).GetField("<CreatedDateTime>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));

            var currentCircleOrderIndex = runtimeEntityType.AddProperty(
                "CurrentCircleOrderIndex",
                typeof(uint),
                propertyInfo: typeof(ToDoEntity).GetProperty("CurrentCircleOrderIndex", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ToDoEntity).GetField("<CurrentCircleOrderIndex>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0u);

            var daysOffset = runtimeEntityType.AddProperty(
                "DaysOffset",
                typeof(ushort),
                propertyInfo: typeof(ToDoEntity).GetProperty("DaysOffset", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ToDoEntity).GetField("<DaysOffset>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: (ushort)0);

            var description = runtimeEntityType.AddProperty(
                "Description",
                typeof(string),
                propertyInfo: typeof(ToDoEntity).GetProperty("Description", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ToDoEntity).GetField("<Description>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 10000);

            var descriptionType = runtimeEntityType.AddProperty(
                "DescriptionType",
                typeof(DescriptionType),
                propertyInfo: typeof(ToDoEntity).GetProperty("DescriptionType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ToDoEntity).GetField("<DescriptionType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            descriptionType.SetSentinelFromProviderValue((byte)0);

            var dueDate = runtimeEntityType.AddProperty(
                "DueDate",
                typeof(DateOnly),
                propertyInfo: typeof(ToDoEntity).GetProperty("DueDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ToDoEntity).GetField("<DueDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateOnly(1, 1, 1));

            var icon = runtimeEntityType.AddProperty(
                "Icon",
                typeof(string),
                propertyInfo: typeof(ToDoEntity).GetProperty("Icon", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ToDoEntity).GetField("<Icon>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var isBookmark = runtimeEntityType.AddProperty(
                "IsBookmark",
                typeof(bool),
                propertyInfo: typeof(ToDoEntity).GetProperty("IsBookmark", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ToDoEntity).GetField("<IsBookmark>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var isCompleted = runtimeEntityType.AddProperty(
                "IsCompleted",
                typeof(bool),
                propertyInfo: typeof(ToDoEntity).GetProperty("IsCompleted", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ToDoEntity).GetField("<IsCompleted>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var isFavorite = runtimeEntityType.AddProperty(
                "IsFavorite",
                typeof(bool),
                propertyInfo: typeof(ToDoEntity).GetProperty("IsFavorite", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ToDoEntity).GetField("<IsFavorite>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var isRequiredCompleteInDueDate = runtimeEntityType.AddProperty(
                "IsRequiredCompleteInDueDate",
                typeof(bool),
                propertyInfo: typeof(ToDoEntity).GetProperty("IsRequiredCompleteInDueDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ToDoEntity).GetField("<IsRequiredCompleteInDueDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var lastCompleted = runtimeEntityType.AddProperty(
                "LastCompleted",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(ToDoEntity).GetProperty("LastCompleted", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ToDoEntity).GetField("<LastCompleted>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var link = runtimeEntityType.AddProperty(
                "Link",
                typeof(string),
                propertyInfo: typeof(ToDoEntity).GetProperty("Link", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ToDoEntity).GetField("<Link>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 1000);

            var monthlyDays = runtimeEntityType.AddProperty(
                "MonthlyDays",
                typeof(string),
                propertyInfo: typeof(ToDoEntity).GetProperty("MonthlyDays", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ToDoEntity).GetField("<MonthlyDays>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var monthsOffset = runtimeEntityType.AddProperty(
                "MonthsOffset",
                typeof(ushort),
                propertyInfo: typeof(ToDoEntity).GetProperty("MonthsOffset", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ToDoEntity).GetField("<MonthsOffset>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: (ushort)0);

            var name = runtimeEntityType.AddProperty(
                "Name",
                typeof(string),
                propertyInfo: typeof(ToDoEntity).GetProperty("Name", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ToDoEntity).GetField("<Name>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 255);

            var normalizeName = runtimeEntityType.AddProperty(
                "NormalizeName",
                typeof(string),
                propertyInfo: typeof(ToDoEntity).GetProperty("NormalizeName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ToDoEntity).GetField("<NormalizeName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 255);

            var orderIndex = runtimeEntityType.AddProperty(
                "OrderIndex",
                typeof(uint),
                propertyInfo: typeof(ToDoEntity).GetProperty("OrderIndex", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ToDoEntity).GetField("<OrderIndex>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0u);

            var parentId = runtimeEntityType.AddProperty(
                "ParentId",
                typeof(Guid?),
                propertyInfo: typeof(ToDoEntity).GetProperty("ParentId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ToDoEntity).GetField("<ParentId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var referenceId = runtimeEntityType.AddProperty(
                "ReferenceId",
                typeof(Guid?),
                propertyInfo: typeof(ToDoEntity).GetProperty("ReferenceId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ToDoEntity).GetField("<ReferenceId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var remindDaysBefore = runtimeEntityType.AddProperty(
                "RemindDaysBefore",
                typeof(uint),
                propertyInfo: typeof(ToDoEntity).GetProperty("RemindDaysBefore", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ToDoEntity).GetField("<RemindDaysBefore>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0u);

            var type = runtimeEntityType.AddProperty(
                "Type",
                typeof(ToDoType),
                propertyInfo: typeof(ToDoEntity).GetProperty("Type", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ToDoEntity).GetField("<Type>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            type.SetSentinelFromProviderValue(0);

            var typeOfPeriodicity = runtimeEntityType.AddProperty(
                "TypeOfPeriodicity",
                typeof(TypeOfPeriodicity),
                propertyInfo: typeof(ToDoEntity).GetProperty("TypeOfPeriodicity", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ToDoEntity).GetField("<TypeOfPeriodicity>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            typeOfPeriodicity.SetSentinelFromProviderValue((byte)0);

            var weeklyDays = runtimeEntityType.AddProperty(
                "WeeklyDays",
                typeof(string),
                propertyInfo: typeof(ToDoEntity).GetProperty("WeeklyDays", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ToDoEntity).GetField("<WeeklyDays>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var weeksOffset = runtimeEntityType.AddProperty(
                "WeeksOffset",
                typeof(ushort),
                propertyInfo: typeof(ToDoEntity).GetProperty("WeeksOffset", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ToDoEntity).GetField("<WeeksOffset>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: (ushort)0);

            var yearsOffset = runtimeEntityType.AddProperty(
                "YearsOffset",
                typeof(ushort),
                propertyInfo: typeof(ToDoEntity).GetProperty("YearsOffset", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ToDoEntity).GetField("<YearsOffset>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: (ushort)0);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "ToDos");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
